---
 - name: Install default packages for PHP WEB Server
   package:
        name: "{{ item }}"
        update_cache: yes
        state: present
   with_items:
   - httpd
   - php
   - php-mysql
   - php-pear
